const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
const GET_INITIAL_POSTS = "GET_INITIAL_POSTS";
const SET_LOADING = "SET_LOADING";
const SET_ERRORS = "SET_ERRORS";

export { INCREMENT, DECREMENT, GET_INITIAL_POSTS, SET_LOADING, SET_ERRORS };
